name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write # Required for pushing to the output branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dist directory
        run: mkdir -p dist

      - name: Generate snake SVG
        uses: Platane/snk@v0.0.16
        id: snake-gif
        with:
          github_user_name: samarajit01
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Verify generated file
        run: ls -l dist/github-contribution-grid-snake.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist